'use strict';
const $=id=>document.getElementById(id),opened=new Set(),extinguished=new Set();let stage='welcome',activeBox=null,ghostTimer=null,returnFocus=null,hold=null;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
for(let i=0;i<75;i++){const s=document.createElement('i');s.className='star';const size=Math.random()*2+1;s.style.cssText=`left:${Math.random()*100}%;top:${Math.random()*100}%;width:${size}px;height:${size}px;animation-delay:${Math.random()*6}s`; $('stars').append(s)}
const items=[{type:'fortune',title:'舒涵今日专属签',text:'新的一岁，想做的事都有勇气开始，想要的快乐都慢慢靠近。'},{type:'photo',title:'拆到一份可爱',photo:'photo1',text:'这份可爱不用限量，今天的主角就是你。'},{type:'fortune',title:'好运正在派送',text:'烦恼少一点，笑容多一点。接下来的每一天，都有小小的好事发生。'},{type:'photo',title:'今日份闪闪发光',photo:'photo2',text:'不用成为别人眼里的满分，做你自己就已经很好。'},{type:'ghost',title:'捉到鬼有奖励！'},{type:'message',title:'假装是个空盒子',text:'骗你的！里面装了满满的祝福：愿你吃得开心、睡得香，遇见的人和事都温柔。'},{type:'photo',title:'一张快乐收藏',photo:'photo3',text:'把这一刻收藏起来。以后的日子，也要多留下这样的笑容。'},{type:'message',title:'送你一颗快乐星星',text:'愿你一直有喜欢的事、聊得来的朋友，还有说走就走的好心情。生日快乐，程舒涵同学！'}];
function showStage(next){stage=next;['welcome','boxes','final'].forEach(x=>$(x).classList.toggle('hidden',x!==next));window.scrollTo(0,0)}$('start').onclick=()=>showStage('boxes');
function update(){ $('count').textContent=`已开启 ${opened.size} / 8`;$('last').classList.toggle('hidden',opened.size!==8);if(opened.size===8)$('box-note').textContent='所有惊喜收好，还有最后一份祝福。'}
function complete(i){opened.add(i);const b=$('gift-grid').children[i];b.classList.add('open');b.disabled=true;b.setAttribute('aria-label',`第${i+1}个盲盒，已开启`);update()}
function stopGhost(){clearInterval(ghostTimer);ghostTimer=null}function closeModal(){stopGhost();$('modal').close();returnFocus?.focus()}
function photoContent(item){return `<h3>${item.title}</h3><img class="modal-image" src="assets/${item.photo}.jpg" alt="程舒涵的照片"><p class="modal-caption">${item.text}</p><button class="gold modal-button" id="receive">收下这份惊喜</button>`}
function openBox(i){if(stage!=='boxes'||opened.has(i))return false;activeBox=i;returnFocus=$('gift-grid').children[i];const item=items[i],content=$('modal-content');if(item.type==='ghost'){content.innerHTML='<h3>捉到鬼有奖励！</h3><p class="sub">点一下这个小淘气，看看它藏了什么。</p><div class="ghost-field"><button class="ghost" id="ghost" aria-label="捉住小鬼">👻</button></div>';const move=()=>{const g=$('ghost');if(g){g.style.left=`${Math.random()*65}%`;g.style.top=`${Math.random()*55}%`}};ghostTimer=setInterval(move,1400);$('ghost').onclick=()=>{stopGhost();complete(i);content.innerHTML=photoContent({title:'捉到了可爱的你',photo:'caught',text:'抓到啦！这份可爱，今天必须好好收藏。'});$('receive').onclick=closeModal;celebrate(1800)}}else{complete(i);if(item.type==='photo'){content.innerHTML=photoContent(item);$('receive').onclick=closeModal}else if(item.type==='fortune'){content.innerHTML=`<h3>✧ ${item.title}</h3><p class="sub">心诚则灵，全是上上签</p><p class="fortune">${item.text}</p><button class="gold modal-button" id="draw">再求一签</button>`;const fortunes=[item.text,'今天适合许愿，因为好运已经站在你这边。','所期待的会到来，所努力的会开花。慢慢来，也没关系。'];let n=0;$('draw').onclick=()=>{n=(n+1)%fortunes.length;content.querySelector('.fortune').textContent=fortunes[n]}}else{content.innerHTML=`<h3>✧ ${item.title}</h3><p class="fortune">${item.text}</p><button class="gold modal-button" id="receive">收下祝福</button>`;$('receive').onclick=closeModal}}$('modal').showModal();return true}
items.forEach((item,i)=>{const b=document.createElement('button');b.className='gift';b.setAttribute('aria-label',`打开第${i+1}个盲盒`);b.innerHTML='<span class="gift-art" aria-hidden="true"></span>';b.onclick=()=>openBox(i);$('gift-grid').append(b)});$('close').onclick=closeModal;$('modal').addEventListener('cancel',()=>stopGhost());$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeModal()});
$('last').onclick=()=>{if(opened.size===8)showStage('final')};
function blow(i){if(stage!=='final'||extinguished.has(i))return;extinguished.add(i);const c=document.querySelector(`[data-candle="${i}"]`);c.classList.add('out');c.setAttribute('aria-label','蜡烛已经吹灭');c.disabled=true;if(extinguished.size===3){$('candle-note').textContent='愿望已经出发，美好正在赶来。';$('birthday-message').classList.remove('hidden');celebrate(7000)}else $('candle-note').textContent=`还剩 ${3-extinguished.size} 根蜡烛，再吹一下。`}
document.querySelectorAll('.candle').forEach((b,i)=>{b.onclick=()=>blow(i);b.onpointerdown=()=>{hold=setTimeout(()=>blow(i),650)};['pointerup','pointercancel','pointerleave'].forEach(x=>b.addEventListener(x,()=>clearTimeout(hold)))});$('again').onclick=()=>celebrate(7000);
const canvas=$('fireworks'),ctx=canvas.getContext('2d');let particles=[],raf=0,until=0,lastLaunch=0;function resize(){canvas.width=innerWidth*devicePixelRatio;canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}resize();addEventListener('resize',resize);function burst(x,y){const colors=['#ff8cb3','#ebcc86','#bca7f4','#86dece','#f3f5ff'];const color=colors[Math.floor(Math.random()*colors.length)];for(let j=0;j<65;j++){const a=Math.PI*2*j/65,v=1+Math.random()*3.2;particles.push({x,y,vx:Math.cos(a)*v,vy:Math.sin(a)*v,life:1,color})}}
function frame(t){ctx.clearRect(0,0,innerWidth,innerHeight);if(t<until&&t-lastLaunch>550){burst(innerWidth*(.15+Math.random()*.7),innerHeight*(.1+Math.random()*.5));lastLaunch=t}particles=particles.filter(p=>p.life>0);for(const p of particles){p.x+=p.vx;p.y+=p.vy;p.vy+=.018;p.vx*=.992;p.life-=.012;ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,2,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;if(t<until||particles.length)raf=requestAnimationFrame(frame);else{raf=0;ctx.clearRect(0,0,innerWidth,innerHeight)}}function celebrate(ms){until=performance.now()+(reduced?700:ms);if(!raf)raf=requestAnimationFrame(frame)}
const context=document.modelContext;if(context?.registerTool){const lifecycle=new AbortController();const register=t=>{try{Promise.resolve(context.registerTool(t,{signal:lifecycle.signal})).catch(()=>{})}catch{}};register({name:'read_birthday_progress',description:'Read the current birthday surprise stage and completed boxes.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({stage,opened:[...opened],candlesOut:[...extinguished]})});register({name:'open_birthday_box',description:'Open one unopened birthday box on the visible blind-box screen.',inputSchema:{type:'object',properties:{box:{type:'integer',minimum:1,maximum:8}},required:['box'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!Number.isInteger(input?.box)||input.box<1||input.box>8)throw Error('Box must be 1–8');if($('modal').open)throw Error('Close the current surprise first');if(!openBox(input.box-1))throw Error('Box unavailable');return{opened:[...opened],surprise:items[input.box-1].type}}});addEventListener('pagehide',()=>lifecycle.abort(),{once:true})}
